name: Website deployment

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
#     - name: Install dependencies
#       run: npm i
#     - name: Scrape website
#       run: npm run scrape
#     - name: Deploy to Firebase
#       run: npm run deploy
    - run: mkdir -p release && zip --junk-paths release/website-${GITHUB_REF##*/} package.json
    - uses: AButler/upload-release-assets@v1.0
      with:
        files: 'release/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag	: GITHUB_REF
