name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: ls
      - run: node -e "throw new Error('asd')"
      - run: ls -l
      - name: Discord failure notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The website deployment has failed. See results here: https://github.com/Moonlet/website/actions'
